java_library(
    name = "dfu",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:org_jetbrains_annotations",
        "@maven//:com_mojang_datafixerupper",
    ],
)