java_library(
    name = "registry",
    srcs = glob(["**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:dev_hollowcube_minestom_ce",
        "@maven//:net_kyori_adventure_key",
        "@maven//:org_jetbrains_annotations",
        "@maven//:com_mojang_datafixerupper",
        "@maven//:com_google_code_gson_gson",
        "@maven//:org_slf4j_slf4j_api",
    ],
)