java_library(
    name = "item",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/world/rifted/libmmo/registry",
        "//src/main/java/world/rifted/libmmo/dfu",
        "@maven//:net_kyori_adventure_api",
        "@maven//:net_kyori_adventure_key",
        "@maven//:dev_hollowcube_minestom_ce",
        "@maven//:org_jetbrains_annotations",
        "@maven//:com_mojang_datafixerupper",
        "@maven//:com_google_code_gson_gson",
    ],
)