java_library(
    name = "minimessage",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:org_jetbrains_annotations",
        "@maven//:com_mojang_datafixerupper",
        "@maven//:net_kyori_adventure_text_minimessage",
        "@maven//:net_kyori_adventure_api"
    ],
)